# Uncomment the next line to define a global platform for your project
source 'git@github.com:MMSuperD/FANSpec.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'SwiftClassDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftClassDemo
  pod 'FANBaseConfig'
#  pod 'FANBaseConfig',:path => '/Users/fan/Desktop/MyStudy/MyGithub/FANBaseConfig'
  
  pod 'JXSegmentedView'
  
  pod 'Alamofire'

end
